A new Plugin and a fix for the Telegram Plugin
davidmckenzie/pagermon pull request #556
Opened 2023-05-12 21:06 UTC by alphaO4

# Description

I did two things. 
First I created a completly new Plugin, called Meshtastics LoRa API.
This Plugin uses the [python CLI](https://meshtastic.org/docs/software/python/cli) from Meshtastic to send messages to certain chat ID's. This is extremly usefull for cases where there might not be a working cellular connection, since these Meshtastic devices work completle OffTheGrid. 

Dependencies: Meshtastics Python CLI

The Second thing is, that I updated the Telegram Plugin to be able to handle multible chat-id's.
This is usefull in case you don't want to create a Telegram group, or you want to send different Alarms to multible Telegram Users/Groups.
Both, Users and Groups can be given simultainiously. (Tho only in ID form)
Please note, that I disabled the Markdown in "sendMessage()", since it caused an escape character error with encrypted POCSAG messages, that had an escape character. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] This change requires a documentation update

# How Has This Been Tested?

I tested this both under test conditions (with the ./sampleMessage.sh) and under real world continions. 
These changes are now running for a week in a "prod" enviroment, without any problems.

- [ X ] Using ./testMessage.sh to trigger aliases and therefore Messages
- [ X ] Letting it run in prod

# Checklist:

- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated changelog.md with changes made

2023-05-12 21:11 UTC, alphaO4 commented
This also closes the branch "[eature-telegram-multiple-targets](https://github.com/pagermon/pagermon/tree/feature-telegram-multiple-targets)"

2023-05-13 03:43 UTC, DanrwAU commented
We don't merge directly into master, please modify to merge into develop first.

2023-05-13 03:47 UTC, DanrwAU requested changes
Few changes there @marshyonline @davidmckenzie can you take a look for anything i've missed :-)

2023-05-13 03:47 UTC, DanrwAU commented on server/plugins/MeshtasticsLoRaAPI.js
> +    const command = `/home/pi/.local/bin/meshtastic --sendtext "${data.message}"  --ch-index ${data.pluginconf.MeshtasticsLoRaAPI.channelID}`;
This isn't going to work cross platform or even cross user accounts, needs to be fixed.

2023-05-13 03:47 UTC, DanrwAU commented on CHANGELOG.md
> +# 0.3.12b - 2023-05-12
Adding featurs would not be a B release. 

Releases are done by the team, add as Unreleased please, also follow the format below, add the PR number and @ tag of the author

2023-05-13 03:47 UTC, DanrwAU commented on server/plugins/MeshtasticsLoRaAPI.json
> +    "description": "Integration for LoRa, utilising the provided HTTP API. <br>For it to work, you need to specify a chatURL file once on the Host. <br>To do this run: 'meshtastic --set-url https://m
Need to add any pre-requisites the user requires as well, such as the python cli you are using.

2023-05-13 03:47 UTC, geelongmicrosoldering commented
We will also likely need to vigorously test the telegram plugin changes. Not because theres something wrong with your code, but because we actually had a multi destination telegram plugin and had to frantically revert it for.. reasons.

2023-05-13 05:51 UTC, alphaO4 commented
Perfekt, I will make the changes as soon as I'm home from work.

2023-05-13 05:59 UTC, alphaO4 commented
> We will also likely need to vigorously test the telegram plugin changes. Not because theres something wrong with your code, but because we actually had a multi destination telegram plugin and had to frantically revert it for.. reasons.

So far, I didn't have any problems, with regular Strings, of any length. 
What where the problems you guys encountered?

2023-05-13 06:10 UTC, alphaO4 commented on server/plugins/MeshtasticsLoRaAPI.js
> +    const command = `/home/pi/.local/bin/meshtastic --sendtext "${data.message}"  --ch-index ${data.pluginconf.MeshtasticsLoRaAPI.channelID}`;
How do you propose to make this crossplattform?
I thought about maybe adding a field in the settings asking for the path to Meshtastic. 
The problem with that tho, is that the user could give a path to any code, making the app vulnerable to a RCE.

Atleast for most Linux/Mac devices, you can use `${HOME}` or `~`. 
But adding support for Windows, could be quite complicated since the installation path could be vastly different for each user and used Python version.

2023-09-17 07:04 UTC, DanrwAU commented on server/plugins/MeshtasticsLoRaAPI.js
> +    const command = `/home/pi/.local/bin/meshtastic --sendtext "${data.message}"  --ch-index ${data.pluginconf.MeshtasticsLoRaAPI.channelID}`;
i don't have a solution for you off the top of my head, issue is currently we don't have any features gated behind an OS wall. (even the shell plugin is cross platform) so i don't think we'd want to go that route. @davidmckenzie @marshyonline  may want to chime in there tho

2023-09-27 12:34 UTC, DanrwAU requested changes

2024-10-14 13:13 UTC, DanrwAU commented
Closing due to inactivity

2024-10-14 13:13 UTC, closed without merging